export const ADICIONA_PROJETOS = 'ADICIONA_PROJETOS'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const ATUALIZA_TAREFA = 'ATUALIZA_TAREFA'
export const REMOVE_TAREFA = 'REMOVE_TAREFA'
export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'

export const NOTIFICAR = 'NOTIFICAR'